[package]
name = "schuss-etl"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "schuss-etl"
path = "src/main.rs"

[[bin]]
name = "upload-blobs"
path = "src/bin/upload-blobs.rs"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
deunicode = "1"
futures-util = "0.3"
indicatif = "0.17"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "gzip", "brotli", "json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "fs", "io-util"] }
unicode-normalization = "0.1"
url = "2"
